#!/usr/bin/env python3
"""anl_link.py: ELF .o -> .anl (ANsiLic binary format, RV32I & Thumb2)"""
import sys, struct, zlib, argparse
from elftools.elf.elffile import ELFFile
from elftools.elf.relocation import RelocationSection
from elftools.elf.sections import SymbolTableSection

ANL_MAGIC       = 0x4C4E417F
ANL_VERSION     = 1
ANL_ARCH_RV32I  = 1
ANL_ARCH_THUMB2 = 2
ANL_F_PIC       = 1 << 0
ANL_F_DYNAMIC   = 1 << 1

SHT_NULL=0; SHT_CODE=1; SHT_RODATA=2; SHT_DATA=3; SHT_BSS=4
SHT_SYMTAB=5; SHT_STRTAB=6; SHT_RELA=7; SHT_DYNSYM=8; SHT_DYNSTR=9

SHF_EXEC=1; SHF_WRITE=2; SHF_ALLOC=4

R_ANL_32=1; R_ANL_PC32=2; R_ANL_THM_CALL=3; R_ANL_ABS32=4
R_ANL_HI20=5; R_ANL_LO12_I=6; R_ANL_CALL=7

# ARM reloc -> ANL reloc
ARM_RELOC_MAP = {
    2:  R_ANL_ABS32,    # R_ARM_ABS32
    3:  R_ANL_PC32,     # R_ARM_REL32
    10: R_ANL_THM_CALL, # R_ARM_THM_CALL
    28: R_ANL_THM_CALL, # R_ARM_THM_JUMP24
}

# RISC-V reloc -> ANL reloc
RISCV_RELOC_MAP = {
    1:  R_ANL_32,       # R_RISCV_32
    2:  R_ANL_PC32,     # R_RISCV_64 (treat as 32 for RV32)
    4:  R_ANL_CALL,     # R_RISCV_JAL
    18: R_ANL_CALL,     # R_RISCV_CALL
    23: R_ANL_HI20,     # R_RISCV_PCREL_HI20
    24: R_ANL_LO12_I,   # R_RISCV_PCREL_LO12_I
    26: R_ANL_HI20,     # R_RISCV_HI20
    27: R_ANL_LO12_I,   # R_RISCV_LO12_I
}

FHDR_FMT  = '<IBBHIHHII II'  # 32 bytes
SHDR_FMT  = '<HHIIIII'       # 24 bytes: 2+2+4+4+4+4+4 = 24
SYM_FMT   = '<IIIBBB B'      # 16 bytes
RELA_FMT  = '<IIi'           # 12 bytes

def pack_fhdr(magic,ver,arch,flags,entry,shnum,shentsz,fsz,crc,symidx,dynidx):
    return struct.pack(FHDR_FMT, magic,ver,arch,flags,entry,shnum,shentsz,fsz,crc,symidx,dynidx)

def pack_shdr(sh_type,sh_flags,sh_offset,sh_size,sh_addr,sh_link,sh_entsize):
    return struct.pack(SHDR_FMT, sh_type,sh_flags,sh_offset,sh_size,sh_addr,sh_link,sh_entsize)

def pack_sym(name,value,size,stype,bind,shndx):
    return struct.pack(SYM_FMT, name,value,size,stype,bind,shndx,0)

def pack_rela(offset,info,addend):
    return struct.pack(RELA_FMT, offset,info,addend)

def crc32_anl(data: bytes) -> int:
    return zlib.crc32(data) & 0xFFFFFFFF

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('input')
    ap.add_argument('output')
    ap.add_argument('--entry', default='main')
    args = ap.parse_args()

    with open(args.input, 'rb') as f:
        elf = ELFFile(f)

        # Detect architecture
        machine = elf.header['e_machine']
        if machine == 'EM_RISCV':
            arch = ANL_ARCH_RV32I
            reloc_map = RISCV_RELOC_MAP
            print(f"Detected RISC-V architecture")
        elif machine == 'EM_ARM':
            arch = ANL_ARCH_THUMB2
            reloc_map = ARM_RELOC_MAP
            print(f"Detected ARM architecture")
        else:
            print(f"ERROR: Unsupported architecture {machine}", file=sys.stderr)
            sys.exit(1)

        # Collect ELF sections
        elf_secs = {s.name: s for s in elf.iter_sections()}

        elf_sec_to_anl = {}   # ELF section index -> ANL section index
        elf_sec_offset = {}   # ELF section index -> byte offset within merged ANL section

        def sec_data_merged(name, anl_idx):
            parts = []
            offset = 0
            for i, s in enumerate(elf.iter_sections()):
                if s.name == name or s.name.startswith(name + '.'):
                    elf_sec_to_anl[i] = anl_idx
                    elf_sec_offset[i] = offset
                    d = bytes(s.data())
                    parts.append(d)
                    offset += len(d)
            return b''.join(parts)

        code_data   = sec_data_merged('.text',   1)
        rodata_data = sec_data_merged('.rodata', 2)
        # Also merge .rodata.str* sections (generated by -mlong-calls / string merging)
        for i, s in enumerate(elf.iter_sections()):
            if s.name.startswith('.rodata.') and i not in elf_sec_to_anl:
                elf_sec_to_anl[i] = 2
                elf_sec_offset[i] = len(rodata_data)
                rodata_data += bytes(s.data())
        data_data   = sec_data_merged('.data',   3)
        bss_size    = 0
        for i, s in enumerate(elf.iter_sections()):
            if s.name == '.bss' or s.name.startswith('.bss.'):
                elf_sec_to_anl[i] = 4
                elf_sec_offset[i] = 0
                bss_size += s.data_size

        # Symbol table
        symtab_sec = elf.get_section_by_name('.symtab')
        if not symtab_sec:
            print("ERROR: no .symtab", file=sys.stderr); sys.exit(1)

        # Build ANL symbol table
        anl_syms = []
        anl_strtab = b'\x00'
        undef_syms = {}  # name -> anl sym index (for dynsym)

        entry_off = 0
        for sym in symtab_sec.iter_symbols():
            name_off = len(anl_strtab)
            anl_strtab += sym.name.encode() + b'\x00'
            shndx = sym['st_shndx']
            if shndx == 'SHN_UNDEF':
                anl_shndx = 0xFF
                undef_syms[sym.name] = len(anl_syms)
            elif isinstance(shndx, int):
                anl_shndx = elf_sec_to_anl.get(shndx, 0)
            else:
                anl_shndx = 0
            stype = {'STT_FUNC':1,'STT_OBJECT':2,'STT_SECTION':3}.get(sym['st_info']['type'],0)
            bind  = {'STB_LOCAL':0,'STB_GLOBAL':1,'STB_WEAK':2}.get(sym['st_info']['bind'],0)
            anl_syms.append(pack_sym(name_off, sym['st_value'], sym['st_size'], stype, bind, anl_shndx))
            if sym.name == args.entry:
                # For ARM Thumb, strip Thumb bit; for RISC-V, use as-is
                entry_off = sym['st_value'] & ~1 if arch == ANL_ARCH_THUMB2 else sym['st_value']

        symtab_data = b''.join(anl_syms)

        # Build dynsym + dynstr for undefined symbols
        dynsym_data = b''
        dynstr_data = b'\x00'
        if undef_syms:
            for name, _ in undef_syms.items():
                noff = len(dynstr_data)
                dynstr_data += name.encode() + b'\x00'
                dynsym_data += pack_sym(noff, 0, 0, 1, 1, 0xFF)

        # Build RELA for .text (handles both .rel.text and .rel.text.* per-function sections)
        rela_data = b''
        for i, sec in enumerate(elf.iter_sections()):
            name = sec.name
            if not (name == '.rel.text' or name == '.rela.text' or
                    name.startswith('.rel.text.') or name.startswith('.rela.text.')):
                continue
            has_addend = name.startswith('.rela')
            # Find which ELF text section this reloc section applies to
            # The sh_info field points to the section being relocated
            linked_text_idx = sec['sh_info']
            base_offset = elf_sec_offset.get(linked_text_idx, 0)
            for rel in sec.iter_relocations():
                r_type = rel['r_info_type']
                anl_type = reloc_map.get(r_type)
                if anl_type is None:
                    print(f"Warning: unsupported relocation type {r_type}", file=sys.stderr)
                    continue
                sym_idx = rel['r_info_sym']
                # For REL (not RELA), read implicit addend from the patch location in code_data
                if has_addend:
                    addend = rel['r_addend']
                else:
                    patch_off = base_offset + rel['r_offset']
                    addend = struct.unpack_from('<i', code_data, patch_off)[0] if patch_off + 4 <= len(code_data) else 0
                r_info  = (sym_idx << 8) | anl_type
                rela_data += pack_rela(base_offset + rel['r_offset'], r_info, addend)

    # --- Layout ---
    SHNUM = 1  # NULL
    shdrs = []
    sec_payloads = []

    def add_sec(sh_type, sh_flags, data, sh_link=0, sh_entsize=0, bss_sz=0):
        nonlocal SHNUM
        idx = SHNUM; SHNUM += 1
        shdrs.append((sh_type, sh_flags, data, sh_link, sh_entsize, bss_sz))
        return idx

    # Reserve index 0 for NULL
    shdrs_list = [(SHT_NULL,0,b'',0,0,0)]  # idx 0

    code_idx   = len(shdrs_list); shdrs_list.append((SHT_CODE,   SHF_EXEC|SHF_ALLOC,  code_data,   0, 0, 0))
    ro_idx     = len(shdrs_list); shdrs_list.append((SHT_RODATA, SHF_ALLOC,            rodata_data, 0, 0, 0))
    data_idx   = len(shdrs_list); shdrs_list.append((SHT_DATA,   SHF_WRITE|SHF_ALLOC, data_data,   0, 0, 0))
    bss_idx    = len(shdrs_list); shdrs_list.append((SHT_BSS,    SHF_WRITE|SHF_ALLOC, b'',         0, 0, bss_size))
    strtab_idx = len(shdrs_list); shdrs_list.append((SHT_STRTAB, 0,                   anl_strtab,  0, 0, 0))
    symtab_idx = len(shdrs_list); shdrs_list.append((SHT_SYMTAB, 0,                   symtab_data, strtab_idx, 16, 0))
    rela_idx   = len(shdrs_list); shdrs_list.append((SHT_RELA,   0,                   rela_data,   symtab_idx, 12, 0))

    dynsym_idx = 0
    if dynsym_data:
        dynstr_idx = len(shdrs_list); shdrs_list.append((SHT_DYNSTR, 0, dynstr_data, 0, 0, 0))
        dynsym_idx = len(shdrs_list); shdrs_list.append((SHT_DYNSYM, 0, dynsym_data, dynstr_idx, 16, 0))

    shnum = len(shdrs_list)
    hdr_sz = 32
    sh_sz  = 24
    data_start = hdr_sz + shnum * sh_sz

    # Assign offsets
    offsets = []
    cur = data_start
    for (sh_type,_,data,_,_,bss_sz) in shdrs_list:
        if sh_type == SHT_NULL:
            offsets.append(0)
        elif sh_type == SHT_BSS:
            offsets.append(0)
        else:
            offsets.append(cur)
            cur += len(data)
    file_size = cur

    flags = ANL_F_PIC
    if dynsym_data:
        flags |= ANL_F_DYNAMIC

    # Build file
    fhdr = pack_fhdr(ANL_MAGIC, ANL_VERSION, arch, flags,
                     entry_off, shnum, sh_sz, file_size, 0, symtab_idx, dynsym_idx)

    sh_bytes = b''
    for i,(sh_type,sh_flags,data,sh_link,sh_entsize,bss_sz) in enumerate(shdrs_list):
        sz = bss_sz if sh_type == SHT_BSS else len(data)
        sh_bytes += pack_shdr(sh_type, sh_flags, offsets[i], sz, 0, sh_link, sh_entsize)

    payload = b''
    for i,(sh_type,_,data,_,_,_) in enumerate(shdrs_list):
        if sh_type not in (SHT_NULL, SHT_BSS):
            payload += data

    raw = fhdr + sh_bytes + payload
    crc = crc32_anl(raw)
    # Patch CRC at offset 20
    raw = raw[:20] + struct.pack('<I', crc) + raw[24:]

    with open(args.output, 'wb') as f:
        f.write(raw)
    print(f"Written {len(raw)} bytes to {args.output} (entry_off=0x{entry_off:x})")

if __name__ == '__main__':
    main()
